name: PocketUmp Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This magic step creates the missing .jar file so gradlew can work
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew assembleDebug
